name: 'carbon_footprint'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'carbon_footprint'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  carbon_footprint:
    staging:
      +materialized: view
    # marts:
    #   +materialized: table

